[build]
  command = "npm run build"
  publish = "web/.next"
  base = "web"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
